/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import niti.PokretanjeServera;

/**
 *
 * @author Korisnik
 */
public class ServerskaForma extends javax.swing.JFrame {
      PokretanjeServera server;
    /**
     * Creates new form PokretanjeServera
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        btnZaustavljanjeServera.setEnabled(false);
        this.setBackground(Color.yellow);
        setTitle("Serverska forma");
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPokretanjeServera = new javax.swing.JButton();
        lblSatusServera = new javax.swing.JLabel();
        btnZaustavljanjeServera = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKonfiguracijaBaze = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokretanjeServera.setText("Pokretanje Servera");
        btnPokretanjeServera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        btnPokretanjeServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokretanjeServeraActionPerformed(evt);
            }
        });

        lblSatusServera.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSatusServera.setText("SERVER NIJE POKRENUT! POKRENITE SERVER!");

        btnZaustavljanjeServera.setText("Zaustavljanje Servera");
        btnZaustavljanjeServera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnZaustavljanjeServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustavljanjeServeraActionPerformed(evt);
            }
        });

        menuKonfiguracijaBaze.setText("Konfiguracija baze");

        jMenuItem1.setText("Izmeni konfiguraciju");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuKonfiguracijaBaze.add(jMenuItem1);

        jMenuBar1.add(menuKonfiguracijaBaze);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPokretanjeServera, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnZaustavljanjeServera, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSatusServera, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblSatusServera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPokretanjeServera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZaustavljanjeServera, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokretanjeServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokretanjeServeraActionPerformed
        if (server == null || !server.isAlive()) {
        //Controller.getInstance.pokreniServer()'
         btnPokretanjeServera.setEnabled(false);
         btnZaustavljanjeServera.setEnabled(true);
        lblSatusServera.setText("SERVER JE POKRENUT!");
        server = new PokretanjeServera();
        server.start();
       // Kontroler.getInstance().pokreniServer();
        
        }
        
        
    }//GEN-LAST:event_btnPokretanjeServeraActionPerformed

    private void btnZaustavljanjeServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustavljanjeServeraActionPerformed
        
        //Controller.getinstance.zaustaviServer();
        if(server.getSs()!=null && server.getSs().isBound()){
             try {
                Kontroler.getInstance().odjaviKorisnike();
                server.getSs().close();
                JOptionPane.showMessageDialog(this, "Server je ugasen, gasenje programa...");
                this.dispose();
                System.exit(0);
                
            } catch (IOException ex) {
                 System.out.println("Neuspesno gasenje servera");
            }
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnZaustavljanjeServeraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        new KonfiguracijaBaze().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokretanjeServera;
    private javax.swing.JButton btnZaustavljanjeServera;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblSatusServera;
    private javax.swing.JMenu menuKonfiguracijaBaze;
    // End of variables declaration//GEN-END:variables
}
