/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package racunForme;

import domen.Artikal;
import domen.Korisnik;
import domen.Racun;
import domen.StavkaRacuna;
import forme.GlavnaForma;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentskiKontroler;
import modeli.ModelTabeleStavkeRacuna;

/**
 *
 * @author Korisnik
 */
public class KreirajRacun extends javax.swing.JFrame {
    int i=1;
    double stanje=0;
    double povracaj=0;
    Korisnik korisnik;
    
    /**
     * Creates new form KreirajRacun
     */
    public KreirajRacun() {
        initComponents();
        srediCmb();
        srediTabelu();
        btnIzmeni.setVisible(false);
        korisnik=KlijentskiKontroler.getInstance().getTrenutniKorisnik();
        setLocationRelativeTo(null);
        txtSifraRacuna.setVisible(false);
       
               
    }

    

    KreirajRacun(Racun racun) {
        initComponents();
        srediCmb();
        //srediTabelu();
        srediPolja(racun);
        btnIzmeni.setVisible(true);
        btnSacuvajRacun.setVisible(false);
        setLocationRelativeTo(null);
        korisnik=KlijentskiKontroler.getInstance().getTrenutniKorisnik();
        setLocationRelativeTo(null);
        obrisiStavke();
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraRacuna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        txtIznosPDV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbArtikli = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaStavki = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtUplaceno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPovracaj = new javax.swing.JTextField();
        btnSacuvajRacun = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnUkloni = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sifra Racuna");

        jLabel2.setText("Ukupan Iznos");

        jLabel3.setText("Iznos PDV");

        cmbArtikli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Artikal");

        jLabel5.setText("Kolicina");

        tabelaStavki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaStavki);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel6.setText("Platio sa:");

        txtUplaceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUplacenoActionPerformed(evt);
            }
        });
        txtUplaceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUplacenoKeyPressed(evt);
            }
        });

        jLabel7.setText("Povracaj");

        btnSacuvajRacun.setText("Sacuvaj Racun");
        btnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajRacunActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnUkloni.setText("Ukloni");
        btnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Sacuvaj Izmene");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jButton1.setText("Meni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodaj)
                            .addComponent(btnUkloni)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbArtikli, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(txtSifraRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIznosPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtUplaceno, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPovracaj, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addComponent(btnOK)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvajRacun)
                .addGap(30, 30, 30)
                .addComponent(btnIzmeni)
                .addGap(186, 186, 186)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbArtikli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUkloni))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSifraRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUplaceno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPovracaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIznosPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIzmeni)
                        .addComponent(btnSacuvajRacun)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUplacenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUplacenoActionPerformed
        // TODO add your handling code here::
    }//GEN-LAST:event_txtUplacenoActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (validacijaKolicine()) {
            
        
        Artikal a= (Artikal) cmbArtikli.getSelectedItem();
        int kolicina=Integer.parseInt(txtKolicina.getText());
        //int redniBroj=i;//
        double cena=a.getCena();
        
        StavkaRacuna stavka= new StavkaRacuna(null, i, kolicina, a);
        ModelTabeleStavkeRacuna mtr=(ModelTabeleStavkeRacuna) tabelaStavki.getModel();
        mtr.dodaj(stavka);
        mtr.refreshTable();
        i=mtr.vratiListu().size()+1;
        
       // i++;//
        
        double ukupanIznos=a.getCena()*kolicina;
       
        stanje=stanje+ukupanIznos;
        txtUkupanIznos.setText(stanje+"");
        txtIznosPDV.setText(stanje*0.2+"");
        }
        else{
            JOptionPane.showMessageDialog(this, "Количина може бити само број");
        }
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajRacunActionPerformed
        try {
            if (validacija()) {
                
            
            ModelTabeleStavkeRacuna mtr=(ModelTabeleStavkeRacuna) tabelaStavki.getModel();
            ArrayList<StavkaRacuna> listaStavki=mtr.vratiListu();
            Racun racun= new Racun();
            racun.setUkupanIznos(stanje);
            racun.setIznosPDV(stanje*0.2);
            racun.setKorisnik(KlijentskiKontroler.getInstance().getTrenutniKorisnik());
            racun.setPovracaj(Double.parseDouble(txtPovracaj.getText()));
            racun.setUplaceno(Double.parseDouble(txtUplaceno.getText()));
            racun.setListaStavki(listaStavki);
            KlijentskiKontroler.getInstance().sacuvajRacun(racun);
            
           
            
            JOptionPane.showMessageDialog(this, "Успешно сачуван рачун!");
            }else{
                JOptionPane.showMessageDialog(this, "Сва поља морају бити попуњена");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Неуспешно сачуван рачун!");
            ex.printStackTrace();
        }
      
      
       
      
    }//GEN-LAST:event_btnSacuvajRacunActionPerformed

    private void txtUplacenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUplacenoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtUplacenoKeyPressed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (validacijaBroja()) {
            double uplaceno=Integer.parseInt(txtUplaceno.getText());
        povracaj=uplaceno-stanje;
        txtPovracaj.setText(povracaj+"");
        }else{
            JOptionPane.showMessageDialog(this, "Поље уплаћено може садржати само бројеве.");
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniActionPerformed
        // TODO add your handling code here:
        
        ModelTabeleStavkeRacuna mt=(ModelTabeleStavkeRacuna) tabelaStavki.getModel();
        StavkaRacuna stavka =mt.stavka(tabelaStavki.getSelectedRow());
        mt.ukloni(tabelaStavki.getSelectedRow());
        
        double iznos=Double.parseDouble(txtUkupanIznos.getText());
        stanje= iznos-stavka.getArtikal().getCena()*stavka.getKolicina();
        txtUkupanIznos.setText(stanje+"");
        txtIznosPDV.setText(stanje*0.2+"");
        
    }//GEN-LAST:event_btnUkloniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            // TODO add your handling code here:
            if(validacija()){
            ModelTabeleStavkeRacuna mtr=(ModelTabeleStavkeRacuna) tabelaStavki.getModel();
            ArrayList<StavkaRacuna> listaStavki=mtr.vratiListu();
            
            Racun racun= new Racun();
            racun.setUkupanIznos(stanje);
            racun.setIznosPDV(stanje*0.2);
            racun.setKorisnik(KlijentskiKontroler.getInstance().getTrenutniKorisnik());
            racun.setPovracaj(Double.parseDouble(txtPovracaj.getText()));
            racun.setUplaceno(Double.parseDouble(txtUplaceno.getText()));
            racun.setSifraRacuna(Integer.parseInt(txtSifraRacuna.getText()));
            racun.setListaStavki(listaStavki);
            
            KlijentskiKontroler.getInstance().izmeniRacun(racun);
     
            JOptionPane.showMessageDialog(this, "Рачун је измењен.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Сва поља морају бити попуњена.");
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Систем не може да измени рачун.");
        }
            
            
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GlavnaForma gf= new GlavnaForma();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSacuvajRacun;
    private javax.swing.JButton btnUkloni;
    private javax.swing.JComboBox<Object> cmbArtikli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaStavki;
    private javax.swing.JTextField txtIznosPDV;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPovracaj;
    private javax.swing.JTextField txtSifraRacuna;
    private javax.swing.JTextField txtUkupanIznos;
    private javax.swing.JTextField txtUplaceno;
    // End of variables declaration//GEN-END:variables

    private void srediCmb() {
        try {
            cmbArtikli.removeAllItems();
            
            ArrayList<Artikal> listaArtikala=KlijentskiKontroler.getInstance().vratiSveArtikle();
            
            for (Artikal artikal : listaArtikala) {
                cmbArtikli.addItem(artikal);
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(KreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void srediTabelu() {
        ModelTabeleStavkeRacuna mtr= new ModelTabeleStavkeRacuna();
        tabelaStavki.setModel(mtr);
    }

    private void srediPolja(Racun racun) {
        try {
            txtIznosPDV.setText(racun.getIznosPDV()+"");
            txtKolicina.setText("");
            txtPovracaj.setText("");
            txtSifraRacuna.setText(racun.getSifraRacuna()+"");
            txtSifraRacuna.setEnabled(false);
            txtUkupanIznos.setText(racun.getUkupanIznos()+"");
            txtUplaceno.setText(racun.getUplaceno()+"");
            ModelTabeleStavkeRacuna mtr=new ModelTabeleStavkeRacuna();
            ArrayList<StavkaRacuna> stavke= KlijentskiKontroler.getInstance().vratiStavkeRacuna(racun);
            for (StavkaRacuna stavkaRacuna : stavke) {
                mtr.dodaj(stavkaRacuna);
            }
            i=mtr.vratiListu().size()+1;
            tabelaStavki.setModel(mtr);
        } catch (Exception ex) {
            Logger.getLogger(KreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("nije dobra lista");
        }
                }

    private void obrisiStavke() {
        try {
            ModelTabeleStavkeRacuna mtr=(ModelTabeleStavkeRacuna) tabelaStavki.getModel();
            ArrayList<StavkaRacuna> listaStavki=mtr.vratiListu();
            KlijentskiKontroler.getInstance().obrisiStavke(listaStavki);
            System.out.println("obrisane");
        } catch (Exception ex) {
            Logger.getLogger(KreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("nova greska");
                    
        }
    }

    

    private boolean validacijaBroja() {
        String regex= "[0-9]+";
        if(txtUplaceno.getText().matches(regex)) {
            return true;
        }
        return false;
    }

    private boolean validacijaKolicine() {
        String regex= "[0-9]+";
        if(txtKolicina.getText().matches(regex)) {
            return true;
        }
        return false;
    }

    private boolean validacija() {
        if (txtIznosPDV.getText().isEmpty() || txtPovracaj.getText().isEmpty() || txtUkupanIznos.getText().isEmpty()
                || txtUplaceno.getText().isEmpty()) {
            return false;
        
        }
        return true;
    }
}
