/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package racunForme;

import domen.Artikal;
import domen.Racun;
import domen.StavkaRacuna;
import forme.GlavnaForma;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentskiKontroler;
import modeli.ModelTabeleRacun2;

/**
 *
 * @author Korisnik
 */
public class UcitajRacune extends javax.swing.JFrame {

    /**
     * Creates new form UcitajRacune
     */
    public UcitajRacune() {
        initComponents();
        try {
            srediTabelu();
        } catch (Exception ex) {
            Logger.getLogger(UcitajRacune.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
    }

    public UcitajRacune(Artikal a) {
        initComponents();
         try {
            srediTabelu(a);
        } catch (Exception ex) {
            Logger.getLogger(UcitajRacune.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRacuni = new javax.swing.JTable();
        btnObrisiRacun = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaRacuni);

        btnObrisiRacun.setText("Obrisi Racun");
        btnObrisiRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiRacunActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jButton1.setText("Meni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addComponent(btnObrisiRacun)
                            .addGap(44, 44, 44)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiRacun)
                    .addComponent(btnIzmeni))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiRacunActionPerformed
        try {
            ModelTabeleRacun2 mt= (ModelTabeleRacun2) tabelaRacuni.getModel();
            Racun racun= mt.vratiRacun(tabelaRacuni.getSelectedRow());
            mt.obrisi(tabelaRacuni.getSelectedRow());
            KlijentskiKontroler.getInstance().obrisiRacun(racun);
            JOptionPane.showMessageDialog(this, "Рачун је успешно обрисан.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да обрише рачун.");
            ex.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_btnObrisiRacunActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
            JOptionPane.showMessageDialog(this, "Систем је учитао рачун!");
            ModelTabeleRacun2 mt= (ModelTabeleRacun2) tabelaRacuni.getModel();
            Racun racun= mt.vratiRacun(tabelaRacuni.getSelectedRow());
            KreirajRacun kr= new KreirajRacun(racun);
            kr.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GlavnaForma gf= new GlavnaForma();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisiRacun;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tabelaRacuni;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu(Artikal artikal) throws Exception {
        ModelTabeleRacun2 mtr= new ModelTabeleRacun2();
        tabelaRacuni.setModel(mtr);
        
        
        ArrayList<Racun> racuni=KlijentskiKontroler.getInstance().vratiRacune();
       
        for (Racun racun1 : racuni) {
             ArrayList<StavkaRacuna> stavke=KlijentskiKontroler.getInstance().vratiStavkeRacuna(racun1);
             for (StavkaRacuna stavkaRacuna : stavke) {
                if(stavkaRacuna.getArtikal().equals(artikal)){
                      mtr.dodaj(racun1);
                }
            }
          
            
        }
        
    }
    
     private void srediTabelu() throws Exception {
        ModelTabeleRacun2 mtr= new ModelTabeleRacun2();
        tabelaRacuni.setModel(mtr);
        
        
        ArrayList<Racun> racuni=KlijentskiKontroler.getInstance().vratiRacune();
        
        for (Racun racun1 : racuni) {
            mtr.dodaj(racun1);
        }
        
    }
}
