/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package artikalForme;

import domen.Artikal;
import domen.Korisnik;
import domen.TipArtikla;
import forme.GlavnaForma;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import kontroler.KlijentskiKontroler;



/**
 *
 * @author Korisnik
 */
public class DodajNoviArtikal extends javax.swing.JFrame {

    /**
     * Creates new form DodajNoviArtikal
     */
    public DodajNoviArtikal() {
        initComponents();
        srediCmb();
        btnIzmeni.setEnabled(false);
        btnIzmeni.setVisible(false);
        txtSifra.setEnabled(false);
        setLocationRelativeTo(null);
        txtSifra.setVisible(false);
        lblSifra.setVisible(false);
        
    }

    DodajNoviArtikal(Artikal a) {
        initComponents();
        srediCmb();
        
        cmbTipArtikla.setSelectedItem(a.getTipArtikla());
       // cmbTipArtikla.setEnabled(false);
        txtBoja.setText(a.getBoja());
        txtMemorija.setText(a.getMemorija());
        txtNaziv.setText(a.getNaziv());
        txtCena.setText(a.getCena()+"");
        btnSacuvaj.setVisible(false);
        btnIzmeni.setEnabled(true);
        btnIzmeni.setVisible(true);
        txtSifra.setText(a.getSifraArtikla()+"");
        txtSifra.setEnabled(false);
        setLocationRelativeTo(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTipArtikla = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        txtBoja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMemorija = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnMeni = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        txtSifra = new javax.swing.JTextField();
        lblSifra = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tip Artikla");

        cmbTipArtikla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Naziv");

        jLabel3.setText("Cena");

        txtCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCenaActionPerformed(evt);
            }
        });

        jLabel5.setText("Boja");

        jLabel6.setText("Memorija");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnMeni.setText("Meni");
        btnMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeniActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Sacuvaj promene");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        lblSifra.setText("Sifra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMemorija, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(txtBoja, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(txtSifra)))
                    .addComponent(lblSifra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMemorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifra)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeni))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeniActionPerformed
       GlavnaForma gf= new GlavnaForma();
       gf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnMeniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Artikal artikal= new Artikal();
        if(validation()){
            if(validationPrice()){
            try {
                
                artikal.setNaziv(txtNaziv.getText());
                artikal.setBoja(txtBoja.getText());
                artikal.setMemorija(txtMemorija.getText());
                artikal.setTipArtikla((TipArtikla) cmbTipArtikla.getSelectedItem());
                artikal.setCena(Double.parseDouble(txtCena.getText()));
                
                
                KlijentskiKontroler.getInstance().sacuvajArtikal(artikal);
                JOptionPane.showMessageDialog(this, "Артикал је креиран!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Систем не може да креира артикал.");
            }
            }else{
                JOptionPane.showMessageDialog(this, "Цена мора бити позитиван број");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Поља морају бити попуњена.");
        }
        
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Artikal artikal= new Artikal();
        if(validation()){
            if(validationPrice()){
            try {
                artikal.setNaziv(txtNaziv.getText());
                artikal.setBoja(txtBoja.getText());
                artikal.setMemorija(txtMemorija.getText());
                artikal.setTipArtikla((TipArtikla) cmbTipArtikla.getSelectedItem());
                artikal.setCena(Double.parseDouble(txtCena.getText()));
                artikal.setSifraArtikla(Integer.parseInt(txtSifra.getText()));
                
                KlijentskiKontroler.getInstance().izmeniArtikal(artikal);
                JOptionPane.showMessageDialog(this, "Артикал је успешно измењен.");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Систем не може да измени податке о артиклу.");
            }}else{
                 JOptionPane.showMessageDialog(this, "Цена мора бити позитиван број");   
             }}else{
            JOptionPane.showMessageDialog(this, "Поља морају бити попуњена.");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCenaActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnMeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbTipArtikla;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JTextField txtBoja;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtMemorija;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    private void srediCmb() {
        JOptionPane.showMessageDialog(this, "Систем је учитао артикал!");
        try {
            cmbTipArtikla.removeAllItems();
            ArrayList<TipArtikla> tipoviArtikala=KlijentskiKontroler.getInstance().vratiTipoveArtikala();
            
            for (TipArtikla tipArtikla : tipoviArtikala) {
                cmbTipArtikla.addItem(tipArtikla);
            }
        } catch (Exception ex) {
            Logger.getLogger(DodajNoviArtikal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private boolean validation() {
        if(txtBoja.getText().isEmpty() || txtMemorija.getText().isEmpty() || 
                txtCena.getText().isEmpty() || txtNaziv.getText().isEmpty() || cmbTipArtikla.getSelectedItem()==null){
            return false;
        }
        return true;
    }

    private boolean validationPrice() {
        if(Integer.parseInt(txtCena.getText())<0 ){
            return false;
        }
        return true;
    }
    }

    

