/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package artikalForme;

import domen.Artikal;
import domen.Racun;
import domen.TipArtikla;
import forme.GlavnaForma;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentskiKontroler;
import modeli.ModelTabeleArtikal;
import racunForme.KreirajRacun;
import racunForme.UcitajRacune;

/**
 *
 * @author Korisnik
 */
public class PretraziArtikal extends javax.swing.JFrame {

    /**
     * Creates new form PretraziArtikal
     */
    public PretraziArtikal() {
        initComponents();
        srediTabelu();
        
        btnPromeniPodatke.setVisible(false);
        setLocationRelativeTo(null);
    }

    public PretraziArtikal(int i) {
        initComponents();
        srediTabelu();
        btnPromeniPodatke.setVisible(true);
        btnObrisi.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnPromeniPodatke = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnPromeniPodatke.setText("Detalji");
        btnPromeniPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniPodatkeActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi Artikal");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jButton5.setText("Meni");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Pretrazi Racune");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(btnPromeniPodatke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(2, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnPromeniPodatke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisi)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromeniPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniPodatkeActionPerformed
        ModelTabeleArtikal mta=(ModelTabeleArtikal) tabela.getModel();
        Artikal a=mta.getSelectedArtikal(tabela.getSelectedRow());
        DodajNoviArtikal dna= new DodajNoviArtikal(a);
        dna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPromeniPodatkeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       GlavnaForma gf= new GlavnaForma();
       gf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            ModelTabeleArtikal mt= (ModelTabeleArtikal) tabela.getModel();
            Artikal a=mt.getSelectedArtikal(tabela.getSelectedRow());
            
            KlijentskiKontroler.getInstance().obrisiArtikal(a);
            osveziTabelu();
            JOptionPane.showMessageDialog(this, "Систем је обрисао артикал.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да обрише артикал.");
        }
        
        
        
        
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ModelTabeleArtikal mta=(ModelTabeleArtikal) tabela.getModel();
        Artikal a=mta.getSelectedArtikal(tabela.getSelectedRow());
        
        UcitajRacune ur= new UcitajRacune(a);
        ur.setVisible(true);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromeniPodatke;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleArtikal mta= new ModelTabeleArtikal();
        tabela.setModel(mta);
    }

    private void osveziTabelu() {
       ModelTabeleArtikal mta=  (ModelTabeleArtikal) tabela.getModel();
       mta.refreshTable();
    }

    
}
